STACK-150-Component-Alerts
OKAMca/stack pull request #117
Opened 2024-05-27 14:23 UTC by poclerson

## Issue Link
https://okamca.atlassian.net/browse/STACK-150

## Implementation details
- [ ] Alerts component should follow the alert pattern https://www.w3.org/WAI/ARIA/apg/patterns/alert/
- [ ] Carousel component should follow the carousel pattern https://www.w3.org/WAI/ARIA/apg/patterns/carousel/
- [ ] Component should be fully stylable (theme name, tokens)
- [ ] Component should have a story
- [ ] Component button/children props should be replaceable
- [ ] Component should have a callback for opening/closing the alerts

## PR Checklist      
- [ ] Lint must pass
- [ ] Build must pass
- [ ] There should be no warnings/errors in the console/terminal (check locally)

## How to test this PR
- Storybook

2024-05-28 17:11 UTC, mykimd commented
> ## Question
> * Should the component support pagination and/or other react swiper features or do we want this to always be a carousel with next/prev buttons?

Would it be easy to add props to support them? If not, it can be done in another story if needed for another project.

2024-05-28 17:49 UTC, mykimd requested changes

2024-05-28 17:49 UTC, mykimd commented on libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
Ajouter un story avec qu'une seule alerte

2024-05-30 14:15 UTC, poclerson commented
> @poclerson Je ne sais pas si tu as vu mes commentaires?

@mykimd Yes je fais ca aujourd'hui

2024-05-30 17:46 UTC, mykimd approved these changes

2024-05-30 18:00 UTC, merged