Stack 175 carousel accessibility
OKAMca/stack pull request #142
Opened 2024-07-02 19:25 UTC by poclerson

## Issue Link
https://okamca.atlassian.net/browse/STACK-175

## Implementation details
- [ ] Carousel should use the [carousel accessibility pattern](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/)
- [ ] Carousel should be navigable via keyboard
- [ ] Alerts component should use carousel component

## PR Checklist      
- [ ] Lint must pass
- [ ] Build must pass
- [ ] There should be no warnings/errors in the console/terminal (check locally)

## How to test this PR
- Carousel component
- Alerts component

2024-07-04 20:33 UTC, mykimd commented
@poclerson J'ai ajouté des `<a>` dans les slides en local pour tester. Le focus change la slide en naviguant avec le keyboard à cause que ça focus sur les liens.

2024-07-08 14:13 UTC, poclerson commented
> @poclerson J'ai ajouté des `<a>` dans les slides en local pour tester. Le focus change la slide en naviguant avec le keyboard à cause que ça focus sur les liens.

@mykimd Devrait être fixed

2024-07-08 19:31 UTC, mykimd requested changes
@poclerson Fixer toutes les violations ou incomplete issues dans le tab d'accessiblity des stories de carousel et d'alertes

2024-07-08 19:31 UTC, mykimd commented on libs/stack/stack-ui/src/components/Carousel/index.tsx
> +        {hasNavigation && (
Mettre le NextButton après le Carousel pour avoir le bon ordre de focus

2024-07-23 16:27 UTC, mykimd approved these changes

2024-07-23 20:03 UTC, merged