STACK-138 Flexible Editor Content
OKAMca/stack pull request #145
Opened 2024-07-03 19:42 UTC by JeromeTrottier

## Issue Link
https://okamca.atlassian.net/browse/STACK-138

## Implementation details
- [x] Create flexible editor parser
- [x] Parser should allow for custom blocks and components
- [x] Should use Block dispatcher
- [x] Should be able to restyle components

## PR Checklist      
- [x] Lint must pass
- [ ] Build must pass
- [ ] There should be no warnings/errors in the console/terminal (check locally)

## How to test this PR
- Explanation of how to test this PR with a link when applicable.

2024-07-04 17:34 UTC, poclerson requested changes
Le build de directus-flexible-content ne passe pas
<img width="866" alt="image" src="https://github.com/OKAMca/stack/assets/86995350/0541e55c-d6cb-41d0-ad83-1db053dbb36a">

2024-07-04 17:34 UTC, poclerson commented on apps/demo/app/flexible-editor/page.tsx
> +
J'ai ces warnings sur /flexible-editor

<img width="950" alt="image" src="https://github.com/OKAMca/stack/assets/86995350/d87ea410-41e1-4c73-8a99-c50c0479d1ea">

<img width="968" alt="image" src="https://github.com/OKAMca/stack/assets/86995350/fc1dd983-91d2-4eb4-9a56-6f2a08731907">

Est-ce que ça pourrait valoir la peine d'inclure des remappedAttributes de base qui peuvent si jamais se faire overwrite?

2024-07-04 17:34 UTC, poclerson commented on libs/directus/directus-flexible-content/src/lib/components/RenderNodes/index.tsx
> +'use server'
use server

2024-07-04 17:34 UTC, poclerson commented on libs/directus/directus-flexible-content/src/lib/functions/renderView.ts
> +  // console.log(name, type, serializer)
Retirer

2024-07-04 17:34 UTC, poclerson commented on apps/demo/app/flexible-editor/page.tsx
> +'use server'
Est-ce qu'il y a une raison d'utiliser use server ici? habituellement c'est utilisé pour les [server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations), donc pour les fonctions et non les composants

Si c'est pour du code qui doit etre seulement sur le serveur, plutot utiliser ['server-only'](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment)

2024-07-04 17:34 UTC, poclerson commented on libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
> +'use server'
Même chose pour use server ici

2024-07-04 17:34 UTC, poclerson commented on libs/directus/directus-query/src/lib/request.tsx
> +const GRAPHQL_ENDPOINT = (process.env.NEXT_PUBLIC_GRAPHQL_URL as string) ?? 'https://agencyos.okam.one/graphql'
Même chose ici, pas sur a quel point c'est une bonne idée de hard coder ça comme fallback

2024-07-04 20:52 UTC, JeromeTrottier commented on libs/directus/directus-flexible-content/README.md
> +# directus-flexible-content
Y'a un exemple sur `/flexible-editor`, mais le plus gros de la doc va tourner autour de la creation des collections. Je pense attendre à le faire sur Cepsum pour être sur de pas marquer n'importe quoi et que ce soit frais dans ma tête (la création des collections peut être compliqué parce que plusieurs morceaux fonctionnent ensemble)

2024-07-05 15:01 UTC, poclerson commented on libs/directus/directus-flexible-content/README.md
> +# directus-flexible-content
Créé une tache pour la doc: https://okamca.atlassian.net/browse/STACK-181

2024-07-05 15:02 UTC, poclerson approved these changes

2024-07-05 15:02 UTC, poclerson commented on libs/directus/directus-flexible-content/src/lib/functions/renderView.ts
> +'use server'
Est-ce que use server est voulu ici?

2024-07-05 15:04 UTC, poclerson commented on libs/directus/directus-flexible-content/src/lib/functions/renderView.ts
> +'use server'
À part ça ce serait bon pour merge. @ericokam / @mykimd vouliez vous aussi review? Je crois que anyway ce sera plus rapide bien tester dans cepsum et refaire des modifications plutot que d'essayer de tout tester d'un coup

2024-07-05 15:33 UTC, ericokam commented on libs/directus/directus-flexible-content/src/lib/functions/renderView.ts
> +'use server'
Je suis d'accord 👍 @mykimd qu'en penses-tu ?

2024-07-08 15:12 UTC, merged