Stack 117 nav item directus create a generic nav item linker component
OKAMca/stack pull request #163
Opened 2024-07-22 21:12 UTC by poclerson

## Issue Link

## Implementation details
- [ ] Directus link component should dispatch different types of links
- [ ] useNavigationItems hook should loop recursively through a navigation items structure to create an easier-to-use interface

## PR Checklist      
- [ ] Lint must pass
- [ ] Build must pass
- [ ] There should be no warnings/errors in the console/terminal (check locally)

## How to test this PR
- Demo nextJS app
- /directus-next-component/directus-link
- For more complex testing see the relative PR on cepsum

2024-07-23 15:44 UTC, JeromeTrottier requested changes

2024-07-23 15:44 UTC, JeromeTrottier commented on libs/directus/directus-next-component/src/components/DirectusLink/components/File.tsx
> +      {label}
Pas sur pourquoi le label de File ne s'affiche pas dans l'exemple

2024-07-23 15:44 UTC, JeromeTrottier commented on apps/demo/app/directus-next-component/directus-link/page.tsx
> +              "label": "Grand enfant 1",
```suggestion
              "label": "Petit enfant 1",
```

2024-07-23 15:53 UTC, poclerson commented on libs/directus/directus-next-component/src/components/DirectusLink/components/File.tsx
> +      {label}
J'ai modifié l'example pour que le fichier pointe vers un fichier dans agency OS, si ton NEXT_PUBLIC_IMG_DOMAIN pointe vers agency OS ça devrait fonctionner

2024-07-23 19:18 UTC, JeromeTrottier approved these changes

2024-07-23 19:27 UTC, JeromeTrottier reviewed
J'ai approve, mais enfait il faudrait sûrement que DirectusLink soit un client component, parce que bien qu'il va être présent dans les components ui probablement

2024-07-23 20:04 UTC, ericokam commented
@marie-maxime si tu peux y jeter un oeil quand tu auras un temps stp merci :)

2024-07-25 13:38 UTC, JeromeTrottier commented on libs/directus/directus-next-component/src/hooks/navigation-items.tsx
> +  onNavigationItem: (item: Nullable<TNavigationItems<NavigationItems, Link, Depth>>) => Nullable<TLinks>,
`onNavigationItem` devrait pas retourner `Nullable<TDirectusLinkProps>`? Sinon on fait comment pour ajouter une config par dessus?

2024-07-25 14:06 UTC, marie-maxime requested changes

2024-07-25 14:06 UTC, marie-maxime commented on apps/demo/app/directus-next-component/directus-link/page.tsx
> +import type { TLinks } from 'libs/directus/directus-next-component/src/types/links'
import devrait être `@okam/directus-next-component`

2024-07-25 14:06 UTC, marie-maxime commented on apps/demo/app/directus-next-component/directus-link/page.tsx
> +        <div>{link}</div>
comme on a discuté, il faudrait mettre à jour l'exemple pour que le component render avec lien utilise Anchor (au minimum wrapper theme + react aria)

2024-07-25 14:06 UTC, marie-maxime commented on libs/directus/directus-next-component/src/components/DirectusLink/interface.ts
> +import type { TAnchorPropsProps } from 'libs/stack/stack-ui/src/components/Button/interface'
fix import path

2024-07-25 14:06 UTC, marie-maxime commented on libs/directus/directus-next-component/src/hooks/directus-link.ts
> +import type { TAnchorPropsProps } from 'libs/stack/stack-ui/src/components/Button/interface'
fix import path

2024-07-25 14:12 UTC, poclerson commented on apps/demo/app/directus-next-component/directus-link/page.tsx
> +        <div>{link}</div>
Le prop `link` représente le composant DirectusLink déjà rendered, donc il utilise déjà react aria. Je vais ajouter une implémentation avec `linkProps`

2024-07-25 14:18 UTC, JeromeTrottier commented on libs/directus/directus-next-component/src/components/DirectusLink/index.tsx
>    return <LinkComponent {...rest} />
Ajouter les props reliés au theme au LinkComponent

2024-07-25 14:20 UTC, poclerson commented on libs/directus/directus-next-component/src/components/DirectusLink/index.tsx
>    return <LinkComponent {...rest} />
`useDirectusLink` fait déjà ça

2024-07-25 14:56 UTC, JeromeTrottier commented
@poclerson Ça me semble bon de mon côté

2024-07-25 15:56 UTC, marie-maxime approved these changes

2024-07-25 15:57 UTC, merged