fix: onChange, manual select value modifs, button tokens
OKAMca/stack pull request #21
Opened 2023-07-24 19:42 UTC by JeromeTrottier

https://okamca.atlassian.net/browse/STACK-23

### Requirements 
- [x] onChange callback should be called
- [x] Add setValue to props for manually changing the select’s value
### Where to test
Storybook

2023-08-14 15:09 UTC, poclerson approved these changes

2023-08-15 15:27 UTC, marie-maxime requested changes

2023-08-15 15:27 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +  useEffect(() => {
le use effect ici n'est probablement pas nécessaire.

2023-08-15 15:27 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +  const { triggerProps, menuProps, labelProps } = useSelect({ ...props, onSelectionChange }, state, fieldRef)
`onSelectionChange` doit être passé en param à `useSelectState` pour fonctionner. L'attribution ici ne fait rien (si tu veux tester, tu peux l'enlever et le console log va encore fonctionner dans la story)

2023-08-15 15:27 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +    value,
value devrait être optionnel. L'idée d'avoir un controlled component est bonne mais doit être optionnel.

2023-08-15 15:27 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +    ...props,
il est préférable d'utiliser `...rest` au lieu de directement `...props`. On a beaucoup d'erreur et de warning à cause de `...props`

2023-08-15 16:11 UTC, poclerson commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +  useEffect(() => {
Quand on l'enlève, onSelectionChange ne se fait plus appeler lorsqu'on utilise le Select en tant que controlled component

2023-08-16 14:55 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/Select/Select.tsx
> +  useEffect(() => {
jai commit la modification si tu veux regarder @poclerson

2023-08-16 17:33 UTC, marie-maxime approved these changes

2023-08-16 17:34 UTC, merged