STACK-47-Component-Add-RadioInput-and-RadioGroup
OKAMca/stack pull request #45
Opened 2023-10-06 14:56 UTC by JessicaWillard

2023-10-12 20:24 UTC, marie-maxime requested changes

2023-10-12 20:24 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/RadioGroup/RadioGroup.stories.mdx
> +  <RadioGroupProvider>
RadioGroupProvider est deja utilisé dans le component RadioGroup, enlever celui ici car en double sinon.

2023-10-12 20:24 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/RadioGroup/index.tsx
> +    <div {...radioGroupProps} aria-disabled={isDisabled} className={radioGroupTheme}>
utilise les <Box> components

2023-10-12 20:24 UTC, marie-maxime commented on libs/stack-ui/src/components/fields/RadioGroup/index.tsx
> +}
il faudrait un binding avec react hook form comme pour les autre components de fields

2023-10-16 13:41 UTC, JessicaWillard commented on libs/stack-ui/src/components/fields/RadioGroup/index.tsx
> +    <div {...radioGroupProps} aria-disabled={isDisabled} className={radioGroupTheme}>
Si j'utilise le Box les style et le isDisable variant ne fonctionnent plus et je comprend pas tant pourquoi

2023-10-16 13:54 UTC, JessicaWillard commented on libs/stack-ui/src/components/fields/RadioGroup/index.tsx
> +    <div {...radioGroupProps} aria-disabled={isDisabled} className={radioGroupTheme}>
Nvm, j'ai trouvé ma réponse dans un commentaire que tu avais fait sur une PR d'Antoine

2023-10-17 01:11 UTC, marie-maxime approved these changes

2023-10-17 01:11 UTC, merged