STACK-64-Image-Thumbhash-support
OKAMca/stack pull request #59
Opened 2023-11-17 23:17 UTC by poclerson

2023-11-23 20:48 UTC, marie-maxime commented on libs/stack-ui/src/components/DirectusImage/index.tsx
> +export const Img = (props: TImgProps) => {
le nom du component (DirectusImage) est trop spécifique à une technologie, il faudrait que la partie Directus soit dans une autre component isolée du reste de la gestion du lazy load. 

Le component à 3 renders, trop de if/else pour un component generique

2023-11-23 20:54 UTC, marie-maxime commented on package.json
> +    "unlazy": "^0.10.2",
ajouter la librairie dans vite.config.ts dans "external"

2023-11-23 20:56 UTC, marie-maxime requested changes
pour bien faire les choses, il devrait y avoir une component `<Image />` plus generique sans Directus avec le support pour le lazy load.

Ensuite, une component DirectusImage pourrait être créé à partie de celle ci.

2023-11-24 22:19 UTC, marie-maxime requested changes
ça va pour les changements de components! par contre le export ne semble pas être le bon (DirectusImage vs DirectusImg).

Aussi, quand je test sur l'app demo ça plante. Possible de fixer cela?
Peut-être avoir un exemple de story avec DirectusImg si possible?

2023-11-27 15:18 UTC, poclerson commented
> ça va pour les changements de components! par contre le export ne semble pas être le bon (DirectusImage vs DirectusImg).
> 
> Aussi, quand je test sur l'app demo ça plante. Possible de fixer cela? Peut-être avoir un exemple de story avec DirectusImg si possible?

Je me trompe peut-être, mais avoir un exemple pour DirectusImg demanderait pas d'avoir un CMS de set up pour le stack?

2023-11-27 22:37 UTC, merged