STACK-103-Menu-Context-provider-should-not-use-side-panel-context-provider
OKAMca/stack pull request #80
Opened 2024-01-24 17:48 UTC by poclerson

https://okamca.atlassian.net/browse/STACK-103

## Requirements

- [ ] Menu component should not necessarily be a side panel
- [ ] Menu component should be able to render nested menu items as children or as overlay (side panel)

2024-01-30 20:57 UTC, marie-maxime requested changes

2024-01-30 20:57 UTC, marie-maxime commented on libs/stack/stack-ui/src/components/Menu/Menu.tsx
> +      <Box themeName={`${themeName}.sidePanel.wrapper`}>
pas sûre pour le themeName ici car ce n'est pas un sidePanel

2024-01-30 20:57 UTC, marie-maxime commented on libs/stack/stack-ui/src/components/Menu/Menu.tsx
> +    <PanelTransition isVisible={overlayState?.isOpen}>
Est-ce qu'il ya une raison pourquoi avoir 2 components d'animations ? PanelTransition et TransitionAnimation

2024-01-30 20:57 UTC, marie-maxime commented on libs/stack/stack-ui/src/components/Menu/Menu.tsx
> +          <Box themeName={`${themeName}.sidePanel.container`}>
Il y a 2 `<Box>` ici, est-ce nécessaire d'avoir les 2?

2024-01-31 18:37 UTC, marie-maxime requested changes
il semble y avoir eu une modification quelques parts qui cause un overflow horizontal quand on ouvre le menu side panel

2024-01-31 18:43 UTC, poclerson commented
> il semble y avoir eu une modification quelques parts qui cause un overflow horizontal quand on ouvre le menu side panel

fixed

2024-01-31 20:07 UTC, merged