feat: add dynamic page routing from directus page settings
OKAMca/stack pull request #97
Opened 2024-03-17 21:43 UTC by marie-maxime

## Issue Link
https://okamca.atlassian.net/browse/STACK-118

## Implementation details
- [ ]  Middleware that query page_settings with the path
- [ ]  From the received page_settings, you get both the collection and the individual ID (ex: Programs, ID 578).
- [ ]  Collection can be used to map to a NextJS route folder (ex /programs/[slug]) where slug is the ID from page settings.
- [ ]  Should be a rewrite, not a redirect as for the user, the path received from the CMS is the “right” one.
- [ ]  Provide documentations

## PR Checklist      
- [ ] Lint must pass
- [ ] Build must pass
- [ ] There should no warnings/errors in the console/terminal (check locally)

## How to test this PR
- to do

2024-04-04 13:49 UTC, poclerson commented
@marie-maxime Je suis pas sur comment tester? ou c'est juste checker le code

2024-04-08 13:22 UTC, poclerson commented
@davidpp / @marie-maxime Est-ce qu'on voudrait ajouter une option pour utiliser autre chose que le ID? De ce que je comprends, le id est utilisé ici pour être le plus générique possible, mais dans d'autres projets on pourrait pas vouloir utiliser autre chose?

2024-04-08 13:24 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +    const colletion = get<string>(data, 'page_settings.0.belongs_to_collection')
typo

2024-04-08 13:46 UTC, yanmorinokamca commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +    const colletion = get<string>(data, 'page_settings.0.belongs_to_collection')
colletion -> collection

2024-04-08 13:56 UTC, davidpp commented
> @davidpp / @marie-maxime Est-ce qu'on voudrait ajouter une option pour utiliser autre chose que le ID? De ce que je comprends, le id est utilisé ici pour être le plus générique possible, mais dans d'autres projets on pourrait pas vouloir utiliser autre chose?

Out of scope pour l'instant je dirais.  L'objectif étant d'avoir un retour générique basé sur belongs_to et la clé stocké dans page_settings.  Si un gabarit demande un routing distinct, rien n'empêche de l'implanter dans le projet directement.

2024-04-10 13:30 UTC, poclerson requested changes

2024-04-10 13:30 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +  const graphqlApiKey = process.env.NEXT_API_TOKEN_PUBLIC
Devrait être `NEXT_PUBLIC_API_TOKEN`

2024-04-10 13:30 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +      }
Il y a un `}` de fermeture de trop ici

2024-04-10 13:30 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +    query PageSettings($path: String = null, $lang: String = "fr-CA") {
`lang` ne se fait jamais utiliser, ça fait une erreur graphql

2024-05-02 19:39 UTC, marie-maxime commented
@davidpp @poclerson @yanmorinokamca correction effectué, en attente de review

2024-05-15 19:28 UTC, davidpp commented
@poclerson peux-tu refaire une passe de test/validation suite aux changements de Marie-Maxime.

2024-05-15 20:22 UTC, poclerson requested changes

2024-05-15 20:22 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +  const { pathname, locale } = request.nextUrl
locale est utilisée normalement pour router avec multi domaines, pas avec des préfixes de paths (/fr/..., /en/...) j'ai l'impression?

https://nextjs.org/docs/pages/building-your-application/routing/internationalization#getting-started

On pourrait peut-être avoir une config avec des locales et ça va juste la chercher dans le pathname plutôt

Il faut aussi que je désactive [next-i18n-router](https://github.com/i18nexus/next-i18n-router) sur Vanier pour que ça fonctionne, vu qu'il prend une request et retourne une response. Peut-être qu'il y a moyen de les faire fonctionner ensembles/si on pensait utiliser quelque chose d'autre?

2024-05-15 20:22 UTC, poclerson commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +    return pathName.replace(`/${locale}`, '')
le pathname contient pas de leading `/`, donc ça se fait jamais remplacer (et la locale est undefined)

2024-05-30 18:11 UTC, marie-maxime commented on libs/directus/directus-next-component/src/lib/directus-next-rewrite.ts
> +  const { pathname, locale } = request.nextUrl
(Voir https://locize.com/blog/next-app-dir-i18n/)

2024-06-10 18:59 UTC, poclerson commented
@marie-maxime Changé pour que directusRouteMiddleware prenne des locales, et testé avec https://locize.com/blog/next-app-dir-i18n/

Testé sur https://github.com/OKAMca/vanier-mono/pull/387

2024-06-11 15:51 UTC, merged